import { defineDocs } from "@farming-labs/docs";
import { colorful } from "@farming-labs/theme/colorful";

export default defineDocs({
  entry: "docs",
  theme: colorful(),
  ordering: [
    {
      "slug": "quickstart"
    },
    {
      "slug": "installation"
    },
    {
      "slug": "features",
      "children": [
        {
          "slug": "dashboard-overview"
        },
        {
          "slug": "developer-tools"
        },
        {
          "slug": "event-tracking"
        },
        {
          "slug": "organization-management"
        },
        {
          "slug": "session-management"
        },
        {
          "slug": "user-management"
        }
      ]
    },
    {
      "slug": "self-hosting",
      "children": [
        {
          "slug": "astro"
        },
        {
          "slug": "elysia"
        },
        {
          "slug": "express"
        },
        {
          "slug": "hono"
        },
        {
          "slug": "nextjs"
        },
        {
          "slug": "nuxt"
        },
        {
          "slug": "overview"
        },
        {
          "slug": "remix"
        },
        {
          "slug": "solid-start"
        },
        {
          "slug": "svelte-kit"
        },
        {
          "slug": "tanstack-start"
        }
      ]
    },
    {
      "slug": "configuration",
      "children": [
        {
          "slug": "database-adapters"
        },
        {
          "slug": "database"
        },
        {
          "slug": "deployment"
        },
        {
          "slug": "environment"
        }
      ]
    },
    {
      "slug": "guides",
      "children": [
        {
          "slug": "cli-usage"
        },
        {
          "slug": "watch-mode"
        }
      ]
    },
    {
      "slug": "examples",
      "children": [
        {
          "slug": "astro"
        },
        {
          "slug": "elysia"
        },
        {
          "slug": "express"
        },
        {
          "slug": "hono"
        },
        {
          "slug": "nextjs"
        },
        {
          "slug": "nuxt"
        },
        {
          "slug": "remix"
        },
        {
          "slug": "solid-start"
        },
        {
          "slug": "svelte-kit"
        },
        {
          "slug": "tanstack-start"
        }
      ]
    },
    {
      "slug": "api",
      "children": [
        {
          "slug": "cli",
          "children": [
            {
              "slug": "init"
            },
            {
              "slug": "start"
            }
          ]
        },
        {
          "slug": "config",
          "children": [
            {
              "slug": "runtime"
            }
          ]
        },
        {
          "slug": "exports"
        }
      ]
    }
  ],
  metadata: {
    titleTemplate: "%s – Docs",
    description: "Generated by @farming-labs/docs Cloud",
  },
});
