import { defineDocs } from "@farming-labs/docs";
import { colorful } from "@farming-labs/theme/colorful";

export default defineDocs({
  entry: "docs",
  theme: colorful(),
  ordering: [
    {
      "slug": "quickstart"
    },
    {
      "slug": "installation"
    },
    {
      "slug": "configuration",
      "children": [
        {
          "slug": "database-adapters"
        },
        {
          "slug": "deployment"
        }
      ]
    },
    {
      "slug": "guides",
      "children": [
        {
          "slug": "cli-usage"
        },
        {
          "slug": "watch-mode"
        }
      ]
    },
    {
      "slug": "examples",
      "children": [
        {
          "slug": "astro"
        },
        {
          "slug": "elysia"
        },
        {
          "slug": "express"
        },
        {
          "slug": "hono"
        },
        {
          "slug": "nextjs"
        },
        {
          "slug": "nuxt"
        },
        {
          "slug": "remix"
        },
        {
          "slug": "solid-start"
        },
        {
          "slug": "svelte-kit"
        },
        {
          "slug": "tanstack-start"
        }
      ]
    },
    {
      "slug": "self-hosting",
      "children": [
        {
          "slug": "overview"
        },
        {
          "slug": "astro"
        },
        {
          "slug": "elysia"
        },
        {
          "slug": "express"
        },
        {
          "slug": "hono"
        },
        {
          "slug": "nextjs"
        },
        {
          "slug": "nuxt"
        },
        {
          "slug": "remix"
        },
        {
          "slug": "solid-start"
        },
        {
          "slug": "svelte-kit"
        },
        {
          "slug": "tanstack-start"
        }
      ]
    },
    {
      "slug": "features",
      "children": [
        {
          "slug": "messaging-bot"
        },
        {
          "slug": "organization-management"
        }
      ]
    },
    {
      "slug": "architecture",
      "children": [
        {
          "slug": "overview"
        }
      ]
    },
    {
      "slug": "backend",
      "children": [
        {
          "slug": "systems"
        }
      ]
    },
    {
      "slug": "build",
      "children": [
        {
          "slug": "package-structure"
        }
      ]
    },
    {
      "slug": "cli",
      "children": [
        {
          "slug": "tooling"
        }
      ]
    },
    {
      "slug": "docs",
      "children": [
        {
          "slug": "site"
        }
      ]
    },
    {
      "slug": "frontend",
      "children": [
        {
          "slug": "application"
        }
      ]
    }
  ],
  metadata: {
    titleTemplate: "%s – Docs",
    description: "Generated by @farming-labs/docs Cloud",
  },
});
